### ISSUE TITLE
Code and tech doc review checklist

### ISSUE THREAD

**Issue by heathem** [BrianHooper/annuity_calculator#2]
- [x] Standardize precision across output .csv files
- [x] Introduce Dr. Davendra and Dr. Chin-Mei Chueh in reports
- [x] Add "Index" header to first column in output
- [x] Remove space between $ in example output
- [x] Change "time difference" to "Time elapsed"
- [x] Center plot titles(add " + theme(plot.title = element_text(hjust = 0.5))" at the end of the ggplot command) 
- [x] Change plot colors to light blue
- [x] Death plot axis labels - "Age of death", "Frequency"
- [x] Add contact information (CWU Emails) to report
- [x] Change "yearly" annuity to "monthly"
- [x]  Change images on tech doc to match new output

**Comment by heathem** [comment]
instead of adding "Index" header to first column in output, I just removed the row titles.
